"""
Memorize tool for storing information in long-term memory.
"""

import re
from ...base import BaseTool, ToolResult
from .base import MemoryToolMixin
from ....agent.types import RiskLevel


class MemorizeTool(MemoryToolMixin, BaseTool):
    """Tool to store information in long-term memory."""

    name = "memorize"
    description = """Store important information into long-term memory for future sessions.

When storing name-related information, use the 'name_type' and 'name_value' fields:
- name_type: "user_name" for the user's name, "agent_name" for the agent's name
- name_value: the actual name value

Examples:
- User's name: {"content": "用户的名字是天宇", "name_type": "user_name", "name_value": "天宇"}
- Agent's name: {"content": "我的名字是奥特曼", "name_type": "agent_name", "name_value": "奥特曼"}
"""
    risk_level = RiskLevel.MODERATE  # Write to memory

    def __init__(self, memory=None):
        super().__init__(memory=memory)

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "description": "The information to remember"
                },
                "category": {
                    "type": "string",
                    "enum": ["fact", "preference", "experience", "task", "note"],
                    "description": "Type of memory (default: fact)"
                },
                "importance": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1,
                    "description": "Importance score from 0 to 1 (default: 0.5)"
                },
                "name_type": {
                    "type": "string",
                    "enum": ["user_name", "agent_name"],
                    "description": "Type of name being stored (optional). Use 'user_name' for the user's name, 'agent_name' for the agent's own name."
                },
                "name_value": {
                    "type": "string",
                    "description": "The actual name value (optional). Required if name_type is specified."
                }
            },
            "required": ["content"]
        }

    @property
    def supports_undo(self) -> bool:
        """MemorizeTool supports undo by deleting the stored entry."""
        return True

    def undo(self, undo_data: dict, context: dict) -> bool:
        """
        Undo memorize operation by deleting the entry.

        Args:
            undo_data: Contains entry_id of the stored memory
            context: Contains memory instance

        Returns:
            True if undo was successful
        """
        memory = context.get("memory")
        if not memory:
            return False

        entry_id = undo_data.get("entry_id")
        if not entry_id:
            return False

        # Delete the memory entry
        if hasattr(memory, 'forget'):
            return memory.forget(entry_id)
        elif hasattr(memory, 'long_term_memory'):
            return memory.long_term_memory.delete(entry_id)

        return False

    def execute(self, content: str, category: str = "fact", importance: float = 0.5, name_type: str = None, name_value: str = None) -> ToolResult:
        # Check memory availability
        error = self._check_memory_available()
        if error:
            return error

        try:
            # Build metadata for storage
            storage_metadata = None
            detected_name_type = None
            detected_name_value = None

            # Priority 1: Use explicit name_type and name_value parameters
            if name_type and name_value:
                detected_name_type = name_type
                detected_name_value = name_value
                storage_metadata = {"type": name_type, "value": name_value}

            # Priority 2: Fallback to regex pattern matching
            else:
                # NOTE: memorize content is generated by the Agent (LLM), so:
                # - "我的名字" (my name) refers to the Agent's name
                # - "用户的名字" (user's name) refers to the user's name

                # User name patterns (explicit user reference)
                user_patterns = [
                    r"用户名[是为]\s*([^，。！,.]+)",
                    r"用户的名字[是为]\s*([^，。！,.]+)",
                    r"用户叫\s*([^，。！,.]+)",
                ]
                # Agent name patterns (self-reference or user addressing agent)
                agent_patterns = [
                    r"Agent名[是为]\s*([^，。！,.]+)",
                    r"Agent的名字[是为]\s*([^，。！,.]+)",
                    r"你的名字[是为叫]\s*([^，。！,.]+)",
                    r"你叫\s*([^，。！,.]+)",
                    r"我的名字[是为]\s*([^，。！,.]+)",
                    r"我叫\s*([^，。！,.]+)",
                ]

                for pattern in user_patterns:
                    match = re.search(pattern, content)
                    if match:
                        detected_name_type = "user_name"
                        detected_name_value = match.group(1).strip()
                        break

                if not detected_name_type:
                    for pattern in agent_patterns:
                        match = re.search(pattern, content)
                        if match:
                            detected_name_type = "agent_name"
                            detected_name_value = match.group(1).strip()
                            break

                # Sanitize detected value
                if detected_name_value:
                    try:
                        detected_name_value = detected_name_value.encode('utf-8', errors='replace').decode('utf-8')
                    except (UnicodeDecodeError, UnicodeEncodeError):
                        pass

                # Build metadata for storage if name detected
                if detected_name_type and detected_name_value:
                    storage_metadata = {"type": detected_name_type, "value": detected_name_value}

            # Store in memory with metadata (returns tuple: entry_id, is_new)
            entry_id, is_new = self._memory.memorize(
                content=content,
                category=category,
                importance=importance,
                metadata=storage_metadata
            )

            # Return result with entry_id and name info for CLI callback
            result_metadata = {"entry_id": entry_id, "is_new": is_new}
            if detected_name_type and detected_name_value:
                result_metadata["name_type"] = detected_name_type
                result_metadata["name_value"] = detected_name_value

            if is_new:
                output = f"Successfully stored in long-term memory (ID: {entry_id})"
            else:
                output = f"Updated existing memory (ID: {entry_id})"

            return ToolResult(
                success=True,
                output=output,
                metadata=result_metadata,
                undo_data={"entry_id": entry_id, "is_new": is_new}
            )
        except Exception as e:
            return ToolResult(
                success=False,
                output="",
                error=str(e)
            )
