"""
Memory tools for long-term memory operations.
"""

import re
from .base import BaseTool, ToolResult


class MemorizeTool(BaseTool):
    """Tool to store information in long-term memory."""

    name = "memorize"
    description = """Store important information into long-term memory for future sessions.

When storing name-related information, use the 'name_type' and 'name_value' fields:
- name_type: "user_name" for the user's name, "agent_name" for the agent's name
- name_value: the actual name value

Examples:
- User's name: {"content": "用户的名字是天宇", "name_type": "user_name", "name_value": "天宇"}
- Agent's name: {"content": "我的名字是奥特曼", "name_type": "agent_name", "name_value": "奥特曼"}
"""

    def __init__(self, memory=None):
        self._memory = memory

    def set_memory(self, memory) -> None:
        """Set the memory instance."""
        self._memory = memory

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "content": {
                    "type": "string",
                    "description": "The information to remember"
                },
                "category": {
                    "type": "string",
                    "enum": ["fact", "preference", "experience", "task", "note"],
                    "description": "Type of memory (default: fact)"
                },
                "importance": {
                    "type": "number",
                    "minimum": 0,
                    "maximum": 1,
                    "description": "Importance score from 0 to 1 (default: 0.5)"
                },
                "name_type": {
                    "type": "string",
                    "enum": ["user_name", "agent_name"],
                    "description": "Type of name being stored (optional). Use 'user_name' for the user's name, 'agent_name' for the agent's own name."
                },
                "name_value": {
                    "type": "string",
                    "description": "The actual name value (optional). Required if name_type is specified."
                }
            },
            "required": ["content"]
        }

    def execute(self, content: str, category: str = "fact", importance: float = 0.5, name_type: str = None, name_value: str = None) -> ToolResult:
        if not self._memory:
            return ToolResult(
                success=False,
                output="",
                error="Memory not configured"
            )

        # Check if memory has long-term memory support
        if not hasattr(self._memory, 'memorize'):
            return ToolResult(
                success=False,
                output="",
                error="Long-term memory not available. Use hybrid memory type."
            )

        try:
            # Build metadata for storage
            storage_metadata = None
            detected_name_type = None
            detected_name_value = None

            # Priority 1: Use explicit name_type and name_value parameters
            if name_type and name_value:
                detected_name_type = name_type
                detected_name_value = name_value
                storage_metadata = {"type": name_type, "value": name_value}

            # Priority 2: Fallback to regex pattern matching
            else:
                # NOTE: memorize content is generated by the Agent (LLM), so:
                # - "我的名字" (my name) refers to the Agent's name
                # - "用户的名字" (user's name) refers to the user's name

                # User name patterns (explicit user reference)
                user_patterns = [
                    r"用户名[是为]\s*([^，。！,.]+)",
                    r"用户的名字[是为]\s*([^，。！,.]+)",
                    r"用户叫\s*([^，。！,.]+)",
                ]
                # Agent name patterns (self-reference or user addressing agent)
                agent_patterns = [
                    r"Agent名[是为]\s*([^，。！,.]+)",
                    r"Agent的名字[是为]\s*([^，。！,.]+)",
                    r"你的名字[是为叫]\s*([^，。！,.]+)",
                    r"你叫\s*([^，。！,.]+)",
                    r"我的名字[是为]\s*([^，。！,.]+)",
                    r"我叫\s*([^，。！,.]+)",
                ]

                for pattern in user_patterns:
                    match = re.search(pattern, content)
                    if match:
                        detected_name_type = "user_name"
                        detected_name_value = match.group(1).strip()
                        break

                if not detected_name_type:
                    for pattern in agent_patterns:
                        match = re.search(pattern, content)
                        if match:
                            detected_name_type = "agent_name"
                            detected_name_value = match.group(1).strip()
                            break

                # Sanitize detected value
                if detected_name_value:
                    try:
                        detected_name_value = detected_name_value.encode('utf-8', errors='replace').decode('utf-8')
                    except (UnicodeDecodeError, UnicodeEncodeError):
                        pass

                # Build metadata for storage if name detected
                if detected_name_type and detected_name_value:
                    storage_metadata = {"type": detected_name_type, "value": detected_name_value}

            # Store in memory with metadata
            entry_id = self._memory.memorize(
                content=content,
                category=category,
                importance=importance,
                metadata=storage_metadata
            )

            # Return result with name info for CLI callback
            result_metadata = {"name_type": detected_name_type, "name_value": detected_name_value} if detected_name_type else None

            return ToolResult(
                success=True,
                output=f"Successfully stored in long-term memory (ID: {entry_id})",
                metadata=result_metadata
            )
        except Exception as e:
            return ToolResult(
                success=False,
                output="",
                error=str(e)
            )


class RecallTool(BaseTool):
    """Tool to search long-term memory."""

    name = "recall"
    description = "Search and retrieve information from long-term memory. Use this to recall previously stored preferences, facts, or experiences."

    def __init__(self, memory=None):
        self._memory = memory

    def set_memory(self, memory) -> None:
        """Set the memory instance."""
        self._memory = memory

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "query": {
                    "type": "string",
                    "description": "Search query to find relevant memories"
                },
                "limit": {
                    "type": "integer",
                    "minimum": 1,
                    "maximum": 10,
                    "description": "Maximum number of results (default: 5)"
                }
            },
            "required": ["query"]
        }

    def execute(self, query: str, limit: int = 5) -> ToolResult:
        if not self._memory:
            return ToolResult(
                success=False,
                output="",
                error="Memory not configured"
            )

        # Check if memory has long-term memory support
        if not hasattr(self._memory, 'recall'):
            return ToolResult(
                success=False,
                output="",
                error="Long-term memory not available. Use hybrid memory type."
            )

        try:
            entries = self._memory.recall(query, limit)

            if not entries:
                return ToolResult(
                    success=True,
                    output="No matching memories found."
                )

            # Format results
            results = []
            for i, entry in enumerate(entries, 1):
                results.append(
                    f"{i}. [{entry.category}] {entry.content}\n"
                    f"   (importance: {entry.importance:.1f}, stored: {entry.created_at[:10]})"
                )

            return ToolResult(
                success=True,
                output="Found memories:\n" + "\n".join(results)
            )
        except Exception as e:
            return ToolResult(
                success=False,
                output="",
                error=str(e)
            )


class ListMemoriesTool(BaseTool):
    """Tool to list all long-term memories."""

    name = "list_memories"
    description = "List all stored long-term memories."

    def __init__(self, memory=None):
        self._memory = memory

    def set_memory(self, memory) -> None:
        """Set the memory instance."""
        self._memory = memory

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "category": {
                    "type": "string",
                    "enum": ["fact", "preference", "experience", "task", "note"],
                    "description": "Filter by category (optional)"
                }
            }
        }

    def execute(self, category: str | None = None) -> ToolResult:
        if not self._memory:
            return ToolResult(
                success=False,
                output="",
                error="Memory not configured"
            )

        # Check if memory has long-term memory support
        if not hasattr(self._memory, 'get_all_long_term'):
            return ToolResult(
                success=False,
                output="",
                error="Long-term memory not available. Use hybrid memory type."
            )

        try:
            entries = self._memory.get_all_long_term()

            if category:
                entries = [e for e in entries if e.category == category]

            if not entries:
                return ToolResult(
                    success=True,
                    output="No memories stored yet."
                )

            # Format results
            results = []
            for i, entry in enumerate(entries, 1):
                results.append(
                    f"{i}. [{entry.category}] {entry.content[:100]}{'...' if len(entry.content) > 100 else ''}"
                )

            return ToolResult(
                success=True,
                output=f"Total {len(entries)} memories:\n" + "\n".join(results)
            )
        except Exception as e:
            return ToolResult(
                success=False,
                output="",
                error=str(e)
            )


class ForgetTool(BaseTool):
    """Tool to delete a long-term memory."""

    name = "forget"
    description = "Delete a specific memory from long-term storage by its ID."

    def __init__(self, memory=None):
        self._memory = memory

    def set_memory(self, memory) -> None:
        """Set the memory instance."""
        self._memory = memory

    @property
    def parameters_schema(self) -> dict:
        return {
            "type": "object",
            "properties": {
                "memory_id": {
                    "type": "string",
                    "description": "The ID of the memory to delete (e.g., ltm_abc123)"
                }
            },
            "required": ["memory_id"]
        }

    def execute(self, memory_id: str) -> ToolResult:
        if not self._memory:
            return ToolResult(
                success=False,
                output="",
                error="Memory not configured"
            )

        # Check if memory has long-term memory support
        if not hasattr(self._memory, 'forget'):
            return ToolResult(
                success=False,
                output="",
                error="Long-term memory not available. Use hybrid memory type."
            )

        try:
            success = self._memory.forget(memory_id)

            if success:
                return ToolResult(
                    success=True,
                    output=f"Memory {memory_id} has been deleted."
                )
            else:
                return ToolResult(
                    success=False,
                    output="",
                    error=f"Memory {memory_id} not found."
                )
        except Exception as e:
            return ToolResult(
                success=False,
                output="",
                error=str(e)
            )
